version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-empresa
    environment:
      POSTGRES_DB: empresa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: empresa123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: